// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5GWMcTs9oe9sT7foOsII88qcO7mYzthk',
    appId: '1:1010776831082:android:2562f48fc8b5941402c613',
    messagingSenderId: '1010776831082',
    projectId: 'mynotes-savagenur',
    storageBucket: 'mynotes-savagenur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqIa1X2VMEN5gvdx-ym2-bAecgVohB5M',
    appId: '1:1010776831082:ios:47c942669b09b2dc02c613',
    messagingSenderId: '1010776831082',
    projectId: 'mynotes-savagenur',
    storageBucket: 'mynotes-savagenur.appspot.com',
    iosClientId: '1010776831082-6so74inhgd96vvdobilclqmv9uq7git4.apps.googleusercontent.com',
    iosBundleId: 'com.savagenur.mynotes',
  );
}
